Repository OpenSILEX/phis-ws, pull requests merged in 2018-06, with the labels that each got.

#35 Update pom dependencies. Add jwt to brapi/v1/token service. Fixes #12…
  phis2-ws/pom.xml
  phis2-ws/src/main/java/phis2ws/service/ApplicationInitConfig.java
  phis2-ws/src/main/java/phis2ws/service/authentication/Session.java
  phis2-ws/src/main/java/phis2ws/service/dao/manager/SQLDAO.java
  phis2-ws/src/main/java/phis2ws/service/documentation/DocumentationAnnotation.java
  phis2-ws/src/main/java/phis2ws/service/resources/TokenResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/TokenDTO.java
  phis2-ws/src/main/java/phis2ws/service/utils/ResourcesUtils.java
  phis2-ws/src/main/resources/Phis-JWT-public-key.der
  phis2-ws/src/main/resources/service.properties
Labels: new feature

#62 Sensors
  phis2-ws/src/main/java/phis2ws/service/configuration/URINamespaces.java
  phis2-ws/src/main/java/phis2ws/service/dao/phis/LayerDao.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/AgronomicalObjectDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/PropertyDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/SensorProfileDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/documentation/DocumentationAnnotation.java
  phis2-ws/src/main/java/phis2ws/service/documentation/StatusCodeMsg.java
  phis2-ws/src/main/java/phis2ws/service/resources/SensorResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/PropertyDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/SensorProfileDTO.java
  phis2-ws/src/main/java/phis2ws/service/view/model/phis/Cardinality.java
  phis2-ws/src/main/java/phis2ws/service/view/model/phis/Property.java
  phis2-ws/src/main/java/phis2ws/service/view/model/phis/SensorProfile.java
Labels: new feature

#63 Fixes #61 - Refactoring date function
  phis2-ws/src/main/java/phis2ws/service/configuration/DateFormats.java
  phis2-ws/src/main/java/phis2ws/service/resources/TokenResourceService.java
  phis2-ws/src/main/java/phis2ws/service/utils/ResourcesUtils.java
  phis2-ws/src/main/java/phis2ws/service/utils/dates/Dates.java
Labels: refactoring

#66 Vocabularies - rdfs groups
  phis2-ws/src/main/java/phis2ws/service/configuration/URINamespaces.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/VocabularyDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/resources/VocabularyResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/PropertyVocabularyDTO.java
  phis2-ws/src/main/java/phis2ws/service/view/brapi/form/ResponseFormVocabularyProperty.java
  phis2-ws/src/main/java/phis2ws/service/view/brapi/results/ResultVocabularyProperty.java
  phis2-ws/src/main/java/phis2ws/service/view/model/phis/Property.java
Labels: new feature

#67 vocabularies - contacts
  phis2-ws/src/main/java/phis2ws/service/configuration/URINamespaces.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/UriDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/VocabularyDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/resources/VocabularyResourceService.java
Labels: new feature

#68 Uri generator - For agent uri generation
  phis2-ws/src/main/java/phis2ws/service/configuration/URINamespaces.java
  phis2-ws/src/main/java/phis2ws/service/utils/UriGenerator.java
Labels: new feature

#71 correct DTO rules (references #70)
  phis2-ws/src/main/java/phis2ws/service/resources/dto/AgronomicalObjectDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/DatasetDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/ExperimentDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/GroupDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/ImageMetadataDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/InstanceDefinitionDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/LayerDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/LogoutDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/MethodDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/ProjectDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/PropertyDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/ProvenanceDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/SensorProfileDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/TraitDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/TripletDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/UnitDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/UserDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/VariableDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/WasGeneratedByDTO.java
Labels: minor bug

#72 devices properties (by type) - references #65
  phis2-ws/src/main/java/phis2ws/service/configuration/URINamespaces.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/VocabularyDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/resources/VocabularyResourceService.java
Labels: new feature

#75 update labels form and add comments (references #65)
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/UriDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/VocabularyDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/PropertyVocabularyDTO.java
Labels: new feature
