Repository OpenSILEX/phis-ws, pull requests merged in 2018-08, with the labels that each got.

#93 update license header with the new coding style
  phis2-ws/licenseheader.txt
Labels: enhancement

#77 Add annotation service
  phis2-ws/src/main/java/phis2ws/service/configuration/DateFormats.java
  phis2-ws/src/main/java/phis2ws/service/configuration/URINamespaces.java
  phis2-ws/src/main/java/phis2ws/service/dao/manager/DAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/manager/SQLDAO.java
  phis2-ws/src/main/java/phis2ws/service/dao/phis/UserDaoPhisBrapi.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/AnnotationDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/UriDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/VocabularyDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/documentation/DocumentationAnnotation.java
  phis2-ws/src/main/java/phis2ws/service/json/AnnotationsSerializer.java
  phis2-ws/src/main/java/phis2ws/service/json/CustomJsonWriterReader.java
  phis2-ws/src/main/java/phis2ws/service/model/User.java
  phis2-ws/src/main/java/phis2ws/service/resources/AnnotationResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/UriResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/UserResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/VocabularyResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/AnnotationDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/manager/AbstractVerifiedClass.java
  phis2-ws/src/main/java/phis2ws/service/utils/ResourcesUtils.java
  phis2-ws/src/main/java/phis2ws/service/utils/UriGenerator.java
  phis2-ws/src/main/java/phis2ws/service/utils/sparql/SPARQLQueryBuilder.java
  phis2-ws/src/main/java/phis2ws/service/utils/sparql/SPARQLUpdateBuilder.java
  phis2-ws/src/main/java/phis2ws/service/view/brapi/form/ResponseFormAnnotation.java
  phis2-ws/src/main/java/phis2ws/service/view/brapi/form/ResponseFormVocabularyNamespace.java
  phis2-ws/src/main/java/phis2ws/service/view/brapi/results/ResultAnnotation.java
  phis2-ws/src/main/java/phis2ws/service/view/brapi/results/ResultVocabularyNamespace.java
  phis2-ws/src/main/java/phis2ws/service/view/model/phis/Annotation.java
  phis2-ws/src/main/java/phis2ws/service/view/model/phis/Namespace.java
Labels: new feature

#96 update Result class name
  phis2-ws/src/main/java/phis2ws/service/view/brapi/results/ResultAnnotation.java
  phis2-ws/src/main/java/phis2ws/service/view/brapi/results/ResultStudyDetails.java
  phis2-ws/src/main/java/phis2ws/service/view/brapi/results/ResultVocabularyNamespace.java
Labels: major bug, minor bug

#98 Update login and add anonymous user name / firstname
  phis2-ws/src/main/java/phis2ws/service/documentation/DocumentationAnnotation.java
Labels: refactoring
