Repository OpenSILEX/phis-ws, pull requests merged in 2018-11, with the labels that each got.

#160 Environment - POST
  phis2-ws/src/main/java/phis2ws/service/configuration/DateFormat.java
  phis2-ws/src/main/java/phis2ws/service/dao/mongo/EnvironmentDAOMongo.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/SensorDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/documentation/DocumentationAnnotation.java
  phis2-ws/src/main/java/phis2ws/service/resources/EnvironmentResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/environment/EnvironmentMeasurePostDTO.java
  phis2-ws/src/main/java/phis2ws/service/view/model/phis/EnvironmentMeasure.java
Labels: new feature

#161 swagger-ui: Automatic token handling
  phis2-ws/pom.xml
  phis2-ws/src/main/webapp/api-docs/index.html
Labels: enhancement

#162 fix variables pagination
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/VariableDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/resources/VariableResourceService.java
  phis2-ws/src/main/java/phis2ws/service/view/brapi/form/ResponseFormVariable.java
Labels: P1, major bug

#163 fix uri generator
  phis2-ws/src/main/java/phis2ws/service/utils/UriGenerator.java
Labels: P0, major bug

#164 fix vectors pagination
  phis2-ws/src/main/java/phis2ws/service/resources/VectorResourceService.java
  phis2-ws/src/main/java/phis2ws/service/view/brapi/form/ResponseFormVector.java
Labels: P1, major bug

#167 fix update of users
  phis2-ws/src/main/java/phis2ws/service/dao/phis/UserDaoPhisBrapi.java
Labels: minor bug

#166 Bug correction - Data ordering in Dataset getData service
  phis2-ws/src/main/java/phis2ws/service/dao/mongo/DatasetDAOMongo.java
  phis2-ws/src/main/java/phis2ws/service/resources/DatasetResourceService.java
Labels: P1, minor bug
