Repository OpenSILEX/phis-ws, pull requests merged in 2018-10, with the labels that each got.

#131 fix method creation graph
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/MethodDaoSesame.java
Labels: P0, major bug

#137 Radiometric targets post
  phis2-ws/src/main/java/phis2ws/service/dao/manager/DAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/mongo/DatasetDAOMongo.java
  phis2-ws/src/main/java/phis2ws/service/dao/mongo/ImageMetadataDaoMongo.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/AgronomicalObjectDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/AnnotationDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/PropertyDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/RadiometricTargetDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/SensorDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/TripletDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/VariableDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/documentation/DocumentationAnnotation.java
  phis2-ws/src/main/java/phis2ws/service/ontologies/Contexts.java
  phis2-ws/src/main/java/phis2ws/service/resources/RadiometricTargetResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/PropertiesPostDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/PropertyDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/radiometricTargets/RadiometricTargetPostDTO.java
  phis2-ws/src/main/java/phis2ws/service/utils/UriGenerator.java
  phis2-ws/src/main/java/phis2ws/service/view/model/phis/InstanceDefinition.java
  phis2-ws/src/main/java/phis2ws/service/view/model/phis/Property.java
  phis2-ws/src/main/java/phis2ws/service/view/model/phis/RadiometricTarget.java
Labels: new feature

#146 fix documents - change dublin core ontology uri (# instead of /)
  phis2-ws/src/main/java/phis2ws/service/ontologies/DublinCore.java
Labels: P0, major bug

#147 fix dataset search by date
  phis2-ws/src/main/java/phis2ws/service/resources/DatasetResourceService.java
Labels: P0, major bug

#149 documents update fix
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/DocumentDaoSesame.java
Labels: P0, major bug

#150 remove @URL annotation
  phis2-ws/src/main/java/phis2ws/service/resources/dto/PropertyDTO.java
Labels: P0, major bug

#145 Maven profiles configuration
  phis2-ws/pom.xml
  phis2-ws/src/main/profiles/dev/config.properties
  phis2-ws/src/main/profiles/prod/config.properties
  phis2-ws/src/main/profiles/test/config.properties
  phis2-ws/src/main/resources/js/config.js
  phis2-ws/src/main/resources/mongodb_nosql_config.properties
  phis2-ws/src/main/resources/phis_sql_config.properties
  phis2-ws/src/main/resources/service.properties
  phis2-ws/src/main/resources/sesame_rdf_config.properties
  phis2-ws/src/main/webapp/js/config.js
Labels: new feature

#152 update profiles
  phis2-ws/src/main/profiles/dev/config.properties
  phis2-ws/src/main/resources/sesame_rdf_config.properties
Labels: P2, enhancement

#129 Fix users pagination
  phis2-ws/src/main/java/phis2ws/service/dao/phis/UserDaoPhisBrapi.java
Labels: minor bug

#154 Radiometric target put
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/AgronomicalObjectDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/PropertyDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/RadiometricTargetDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/SensorProfileDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/resources/RadiometricTargetResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/AgronomicalObjectDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/PropertiesPostDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/SensorProfileDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/radiometricTargets/RadiometricTargetDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/rdfResourceDefinition/PropertyDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/rdfResourceDefinition/PropertyPostDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/rdfResourceDefinition/RdfResourceDefinitionDTO.java
Labels: new feature
