Repository OpenSILEX/phis-ws, pull requests merged in 2018-09, with the labels that each got.

#108 Acquisition session - Metadata File
  phis2-ws/src/main/java/phis2ws/service/configuration/URINamespaces.java
  phis2-ws/src/main/java/phis2ws/service/dao/manager/DAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/phis/ExperimentDao.java
  phis2-ws/src/main/java/phis2ws/service/dao/phis/UserDaoPhisBrapi.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/AcquisitionSessionDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/RadiometricTargetDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/SensorDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/VectorDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/documentation/DocumentationAnnotation.java
  phis2-ws/src/main/java/phis2ws/service/resources/AcquisitionSessionResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/brapi/StudyDetailsResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/MetadataFileDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/MetadataFilePhenomobileDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/MetadataFileUAVDTO.java
  phis2-ws/src/main/java/phis2ws/service/view/brapi/form/ResponseFormMetadataFile.java
  phis2-ws/src/main/java/phis2ws/service/view/brapi/results/ResultMetadataFile.java
  phis2-ws/src/main/java/phis2ws/service/view/model/phis/RadiometricTarget.java
Labels: P1, new feature

#116 Fix acquisition session service
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/AcquisitionSessionDAOSesame.java
Labels: P1, minor bug

#115 Acquisition session - metadata file : add pagination
  phis2-ws/src/main/java/phis2ws/service/dao/phis/ExperimentDao.java
  phis2-ws/src/main/java/phis2ws/service/dao/phis/UserDaoPhisBrapi.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/AcquisitionSessionDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/RadiometricTargetDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/SensorDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/VectorDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/resources/AcquisitionSessionResourceService.java
  phis2-ws/src/main/java/phis2ws/service/utils/sparql/SPARQLQueryBuilder.java
  phis2-ws/src/main/java/phis2ws/service/utils/sql/SQLQueryBuilder.java
Labels: major bug

#113 Document count, sort features and document search query optimization
  phis2-ws/src/main/java/phis2ws/service/configuration/SortingValues.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/DocumentDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/documentation/DocumentationAnnotation.java
  phis2-ws/src/main/java/phis2ws/service/resources/DocumentResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/validation/interfaces/SortingValue.java
  phis2-ws/src/main/java/phis2ws/service/resources/validation/validators/SortingValueValidator.java
  phis2-ws/src/main/java/phis2ws/service/utils/sparql/SPARQLQueryBuilder.java
  phis2-ws/src/main/java/phis2ws/service/utils/sparql/SPARQLStringBuilder.java
  phis2-ws/src/main/java/phis2ws/service/view/brapi/form/ResponseFormDocumentMetadata.java
Labels: enhancement

#117 Fix#102
  phis2-ws/src/main/java/phis2ws/service/configuration/URINamespaces.java
  phis2-ws/src/main/java/phis2ws/service/dao/manager/DAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/MethodDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/TraitDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/UnitDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/VariableDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/resources/MethodResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/TraitResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/VariableResourceService.java
Labels: P1, minor bug

#119 Ontologies constants
  phis2-ws/src/main/java/phis2ws/service/configuration/URINamespaces.java
  phis2-ws/src/main/java/phis2ws/service/dao/manager/DAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/mongo/ImageMetadataDaoMongo.java
  phis2-ws/src/main/java/phis2ws/service/dao/phis/DocumentDao.java
  phis2-ws/src/main/java/phis2ws/service/dao/phis/LayerDao.java
  phis2-ws/src/main/java/phis2ws/service/dao/phis/UserDaoPhisBrapi.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/AcquisitionSessionDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/AgronomicalObjectDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/AnnotationDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/DocumentDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/InfrastructureDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/MethodDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/PropertyDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/RadiometricTargetDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/SensorDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/SensorProfileDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/TraitDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/TripletDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/UnitDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/UriDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/VariableDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/VectorDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/VocabularyDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/ontologies/Contexts.java
  phis2-ws/src/main/java/phis2ws/service/ontologies/DublinCore.java
  phis2-ws/src/main/java/phis2ws/service/ontologies/Foaf.java
  phis2-ws/src/main/java/phis2ws/service/ontologies/GeoSPARQL.java
  phis2-ws/src/main/java/phis2ws/service/ontologies/Oa.java
  phis2-ws/src/main/java/phis2ws/service/ontologies/Owl.java
  phis2-ws/src/main/java/phis2ws/service/ontologies/Rdf.java
  phis2-ws/src/main/java/phis2ws/service/ontologies/Rdfs.java
  phis2-ws/src/main/java/phis2ws/service/ontologies/Skos.java
  phis2-ws/src/main/java/phis2ws/service/ontologies/Vocabulary.java
  phis2-ws/src/main/java/phis2ws/service/resources/DocumentResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/ImageResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/InfrastructureResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/TripletsResourceService.java
  phis2-ws/src/main/java/phis2ws/service/utils/DocumentWaitingCheck.java
  phis2-ws/src/main/java/phis2ws/service/utils/UriGenerator.java
  phis2-ws/src/main/java/phis2ws/service/utils/sparql/SPARQLStringBuilder.java
  phis2-ws/src/main/resources/service.properties
  phis2-ws/src/main/resources/sesame_rdf_config.properties
Labels: enhancement, refactoring

#128 Fix bugs v2.6
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/DocumentDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/SensorDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/VectorDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/resources/SensorResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/DataDTO.java
  phis2-ws/src/main/java/phis2ws/service/utils/UriGenerator.java
  phis2-ws/src/main/java/phis2ws/service/view/brapi/form/ResponseFormSensor.java
Labels: P1, major bug
