Repository OpenSILEX/phis-ws, pull requests merged in 2018-03, with the labels that each got.

#34 Manage js librairies. Fixes #30
  phis2-ws/pom.xml
  phis2-ws/src/main/webapp/api-docs/css/print.css
  phis2-ws/src/main/webapp/api-docs/css/reset.css
  phis2-ws/src/main/webapp/api-docs/css/screen.css
  phis2-ws/src/main/webapp/api-docs/css/style.css
  phis2-ws/src/main/webapp/api-docs/css/typography.css
  phis2-ws/src/main/webapp/api-docs/images/collapse.gif
  phis2-ws/src/main/webapp/api-docs/images/expand.gif
  phis2-ws/src/main/webapp/api-docs/images/explorer_icons.png
  phis2-ws/src/main/webapp/api-docs/images/favicon-16x16.png
  phis2-ws/src/main/webapp/api-docs/images/favicon-32x32.png
  phis2-ws/src/main/webapp/api-docs/images/favicon.ico
  phis2-ws/src/main/webapp/api-docs/images/logo_small.png
  phis2-ws/src/main/webapp/api-docs/images/pet_store_api.png
  phis2-ws/src/main/webapp/api-docs/images/throbber.gif
  phis2-ws/src/main/webapp/api-docs/images/wordnik_api.png
  phis2-ws/src/main/webapp/api-docs/index.html
  phis2-ws/src/main/webapp/api-docs/lang/en.js
  phis2-ws/src/main/webapp/api-docs/lang/es.js
  phis2-ws/src/main/webapp/api-docs/lang/fr.js
  phis2-ws/src/main/webapp/api-docs/lang/geo.js
  phis2-ws/src/main/webapp/api-docs/lang/it.js
  phis2-ws/src/main/webapp/api-docs/lang/ja.js
  phis2-ws/src/main/webapp/api-docs/lang/ko-kr.js
  phis2-ws/src/main/webapp/api-docs/lang/pl.js
  phis2-ws/src/main/webapp/api-docs/lang/pt.js
  phis2-ws/src/main/webapp/api-docs/lang/ru.js
  phis2-ws/src/main/webapp/api-docs/lang/tr.js
  phis2-ws/src/main/webapp/api-docs/lang/translator.js
  phis2-ws/src/main/webapp/api-docs/lang/zh-cn.js
  phis2-ws/src/main/webapp/api-docs/lib/backbone-min.js
  phis2-ws/src/main/webapp/api-docs/lib/es5-shim.js
  phis2-ws/src/main/webapp/api-docs/lib/handlebars-4.0.5.js
  phis2-ws/src/main/webapp/api-docs/lib/highlight.9.1.0.pack.js
  phis2-ws/src/main/webapp/api-docs/lib/highlight.9.1.0.pack_extended.js
  phis2-ws/src/main/webapp/api-docs/lib/jquery-1.8.0.min.js
  phis2-ws/src/main/webapp/api-docs/lib/jquery.ba-bbq.min.js
  phis2-ws/src/main/webapp/api-docs/lib/jquery.slideto.min.js
  phis2-ws/src/main/webapp/api-docs/lib/jquery.wiggle.min.js
  phis2-ws/src/main/webapp/api-docs/lib/js-yaml.min.js
  phis2-ws/src/main/webapp/api-docs/lib/jsoneditor.min.js
  phis2-ws/src/main/webapp/api-docs/lib/lodash.min.js
  phis2-ws/src/main/webapp/api-docs/lib/marked.js
  phis2-ws/src/main/webapp/api-docs/lib/object-assign-pollyfill.js
  phis2-ws/src/main/webapp/api-docs/lib/swagger-oauth.js
  phis2-ws/src/main/webapp/api-docs/swagger-ui.js
  phis2-ws/src/main/webapp/api-docs/swagger-ui.min.js
  phis2-ws/src/main/webapp/css/bootstrap-theme.min.css
  phis2-ws/src/main/webapp/css/bootstrap.min.css
  phis2-ws/src/main/webapp/css/style.css
  phis2-ws/src/main/webapp/index.html
  phis2-ws/src/main/webapp/js/.Rhistory
  phis2-ws/src/main/webapp/js/bootstrap.min.js
  phis2-ws/src/main/webapp/js/jquery.min.js
Labels: new fonctionnality, refactoring

#37 Rename logger static variable to LOGGER. Fixes #31
  phis2-ws/src/main/java/phis2ws/service/ApplicationInitConfig.java
  phis2-ws/src/main/java/phis2ws/service/PropertiesFileManager.java
  phis2-ws/src/main/java/phis2ws/service/authentication/SessionThread.java
  phis2-ws/src/main/java/phis2ws/service/authentication/TokenManager.java
  phis2-ws/src/main/java/phis2ws/service/dao/datasource/AbstractSQLDataSource.java
  phis2-ws/src/main/java/phis2ws/service/dao/datasource/DataSourceDAOPhisBrapi.java
  phis2-ws/src/main/java/phis2ws/service/dao/manager/SQLDAO.java
  phis2-ws/src/main/java/phis2ws/service/dao/phis/DocumentDao.java
  phis2-ws/src/main/java/phis2ws/service/dao/phis/SessionDaoPhisBrapi.java
  phis2-ws/src/main/java/phis2ws/service/injection/SessionFactory.java
  phis2-ws/src/main/java/phis2ws/service/json/CustomJsonWriterReader.java
  phis2-ws/src/main/java/phis2ws/service/resources/DocumentResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/TokenResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/ProjectDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/request/filters/AuthentificationRequestFilter.java
  phis2-ws/src/main/java/phis2ws/service/resources/request/filters/CORSResponseFilter.java
  phis2-ws/src/main/java/phis2ws/service/resources/request/filters/PageSizeMaxRequestFilter.java
  phis2-ws/src/main/java/phis2ws/service/utils/DocumentWaitingCheck.java
  phis2-ws/src/main/java/phis2ws/service/utils/FileUploader.java
  phis2-ws/src/main/java/phis2ws/service/utils/JsonConverter.java
Labels: refactoring

#39 Triplets post service
  phis2-ws/pom.xml
  phis2-ws/src/main/java/phis2ws/service/configuration/URINamespaces.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/SensorDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/TripletDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/VectorDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/documentation/DocumentationAnnotation.java
  phis2-ws/src/main/java/phis2ws/service/documentation/StatusCodeMsg.java
  phis2-ws/src/main/java/phis2ws/service/resources/TripletsResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/OType.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/TripletDTO.java
  phis2-ws/src/main/java/phis2ws/service/utils/UriGenerator.java
  phis2-ws/src/main/java/phis2ws/service/view/model/phis/Triplet.java
Labels: new fonctionnality

#42 /uri/{uri}/descendants - returns all descendants
  phis2-ws/src/main/java/phis2ws/service/configuration/URINamespaces.java
Labels: major bug
