Repository OpenSILEX/phis-ws, pull requests merged in 2019-06, with the labels that each got.

#292 Scientificobjects refactor get
  phis2-ws/src/main/java/opensilex/service/dao/DatasetDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/ScientificObjectRdf4jDAO.java
  phis2-ws/src/main/java/opensilex/service/model/ScientificObject.java
  phis2-ws/src/main/java/opensilex/service/resource/ScientificObjectResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/brapi/StudiesResourceService.java
Labels: major bug, refactoring

#293 Optimizations
  phis2-ws/src/main/java/opensilex/service/dao/ActuatorDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/MethodDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/SensorDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/TraitDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/UnitDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/VariableDAO.java
  phis2-ws/src/main/java/opensilex/service/resource/VariableResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/brapi/StudiesResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/brapi/VariableResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/dto/variable/MethodDTO.java
  phis2-ws/src/main/java/opensilex/service/resource/dto/variable/TraitDTO.java
  phis2-ws/src/main/java/opensilex/service/resource/dto/variable/UnitDTO.java
  phis2-ws/src/main/java/opensilex/service/resource/dto/variable/VariableDetailDTO.java
Labels: P1, enhancement

#296 Experiments : fix uri generation
  phis2-ws/src/main/java/opensilex/service/dao/ExperimentSQLDAO.java
  phis2-ws/src/main/java/opensilex/service/utils/UriGenerator.java
Labels: major bug

#297 Documents - remove sftp use
  phis2-ws/src/main/java/opensilex/service/dao/DocumentMongoDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/DocumentRdf4jDAO.java
  phis2-ws/src/main/java/opensilex/service/resource/DocumentResourceService.java
Labels: minor bug

#298 Scientific objects - GET : fix the duplication of properties returned.
  phis2-ws/src/main/java/opensilex/service/dao/ScientificObjectRdf4jDAO.java
Labels: minor bug

#299 Scientific objects post optimization.
  phis2-ws/src/main/java/opensilex/service/dao/ScientificObjectRdf4jDAO.java
  phis2-ws/src/main/java/opensilex/service/utils/UriGenerator.java
Labels: enhancement
