Repository OpenSILEX/phis-ws, pull requests merged in 2019-04, with the labels that each got.

#243 Add mongo db authentication
  phis2-ws/pom.xml
  phis2-ws/src/main/java/phis2ws/service/dao/manager/DAOMongo.java
  phis2-ws/src/main/java/phis2ws/service/resources/request/filters/GenericExceptionMapper.java
  phis2-ws/src/main/profiles/dev/config.properties
  phis2-ws/src/main/resources/mongodb_nosql_config.properties
Labels: enhancement, new feature

#251 GET Variables : Add skos filter
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/VariableDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/documentation/DocumentationAnnotation.java
  phis2-ws/src/main/java/phis2ws/service/resources/VariableResourceService.java
Labels: new feature

#252 Make all Daos inherit DAO.java and set basic dao functions
  phis2-ws/src/main/java/opensilex/service/dao/exception/AggregateException.java
  phis2-ws/src/main/java/opensilex/service/dao/exception/DAODataErrorAggregateException.java
  phis2-ws/src/main/java/opensilex/service/dao/exception/DAODataErrorException.java
  phis2-ws/src/main/java/opensilex/service/dao/exception/ResourceAccessDeniedException.java
  phis2-ws/src/main/java/phis2ws/service/dao/manager/DAO.java
  phis2-ws/src/main/java/phis2ws/service/dao/manager/DAOMongo.java
  phis2-ws/src/main/java/phis2ws/service/dao/manager/DAOPhisBrapi.java
  phis2-ws/src/main/java/phis2ws/service/dao/manager/DAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/manager/SQLDAO.java
  phis2-ws/src/main/java/phis2ws/service/dao/mongo/DataDAOMongo.java
  phis2-ws/src/main/java/phis2ws/service/dao/mongo/DataFileDAOMongo.java
  phis2-ws/src/main/java/phis2ws/service/dao/mongo/DatasetDAOMongo.java
  phis2-ws/src/main/java/phis2ws/service/dao/mongo/DocumentDaoMongo.java
  phis2-ws/src/main/java/phis2ws/service/dao/mongo/EnvironmentDAOMongo.java
  phis2-ws/src/main/java/phis2ws/service/dao/mongo/FileInformationsDAOMongo.java
  phis2-ws/src/main/java/phis2ws/service/dao/mongo/ImageMetadataDaoMongo.java
  phis2-ws/src/main/java/phis2ws/service/dao/mongo/ProvenanceDAOMongo.java
  phis2-ws/src/main/java/phis2ws/service/dao/mongo/ShootingConfigurationDAOMongo.java
  phis2-ws/src/main/java/phis2ws/service/dao/phis/ExperimentDao.java
  phis2-ws/src/main/java/phis2ws/service/dao/phis/GroupDao.java
  phis2-ws/src/main/java/phis2ws/service/dao/phis/LayerDao.java
  phis2-ws/src/main/java/phis2ws/service/dao/phis/ProjectDao.java
  phis2-ws/src/main/java/phis2ws/service/dao/phis/ScientificObjectDAO.java
  phis2-ws/src/main/java/phis2ws/service/dao/phis/SessionDaoPhisBrapi.java
  phis2-ws/src/main/java/phis2ws/service/dao/phis/StudyDAO.java
  phis2-ws/src/main/java/phis2ws/service/dao/phis/UserDaoPhisBrapi.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/AcquisitionSessionDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/AnnotationDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/ConcernedItemDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/DocumentDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/EventDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/ExperimentDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/ImageMetadataDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/InfrastructureDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/MethodDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/PropertyDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/RadiometricTargetDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/ScientificObjectDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/SensorDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/SensorProfileDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/SpeciesDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/TimeDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/TraitDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/TripletDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/UnitDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/UriDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/VariableDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/VectorDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/VocabularyDAOSesame.java
Labels: refactoring

#264 Fix request.filter package issues
  phis2-ws/src/main/java/opensilex/service/resource/request/filter/AuthenticationRequestFilter.java
  phis2-ws/src/main/java/opensilex/service/resource/request/filter/GenericExceptionMapper.java
Labels: refactoring

#256 Put scientific object
  phis2-ws/src/main/java/opensilex/service/dao/DatasetDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/ScientificObjectRdf4jDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/ScientificObjectSQLDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/SensorDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/manager/Rdf4jDAO.java
  phis2-ws/src/main/java/opensilex/service/documentation/DocumentationAnnotation.java
  phis2-ws/src/main/java/opensilex/service/model/ScientificObject.java
  phis2-ws/src/main/java/opensilex/service/ontology/Oeso.java
  phis2-ws/src/main/java/opensilex/service/resource/EnvironmentResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/ScientificObjectResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/dto/scientificObject/ScientificObjectDTO.java
  phis2-ws/src/main/java/opensilex/service/resource/dto/scientificObject/ScientificObjectPostDTO.java
  phis2-ws/src/main/java/opensilex/service/resource/dto/scientificObject/ScientificObjectPutDTO.java
  phis2-ws/src/main/java/opensilex/service/utils/POSTResultsReturn.java
Labels: new feature, refactoring

#259 Event/get annotations service
  phis2-ws/src/main/java/opensilex/service/dao/ConcernedItemDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/EventDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/TimeDAO.java
  phis2-ws/src/main/java/opensilex/service/resource/AnnotationResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/EventResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/dto/event/EventDTO.java
  phis2-ws/src/main/java/opensilex/service/resource/dto/event/EventDetailedDTO.java
Labels: enhancement

#261 Sensors add model
  phis2-ws/src/main/java/opensilex/service/dao/AcquisitionSessionDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/SensorDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/SensorProfileDAO.java
  phis2-ws/src/main/java/opensilex/service/documentation/DocumentationAnnotation.java
  phis2-ws/src/main/java/opensilex/service/model/Sensor.java
  phis2-ws/src/main/java/opensilex/service/ontology/Oeso.java
  phis2-ws/src/main/java/opensilex/service/resource/SensorResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/dto/sensor/SensorDTO.java
  phis2-ws/src/main/java/opensilex/service/resource/dto/sensor/SensorDetailDTO.java
  phis2-ws/src/main/java/opensilex/service/resource/dto/sensor/SensorPostDTO.java
  phis2-ws/src/main/java/opensilex/service/resource/dto/sensor/SensorProfileDTO.java
Labels: new feature, refactoring

#260 Event Annotation/use DAO generic functions
  phis2-ws/src/main/java/opensilex/service/dao/AnnotationDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/ConcernedItemDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/EventDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/PropertyDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/RadiometricTargetDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/SensorProfileDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/TimeDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/VocabularyDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/exception/NotAnAdminException.java
  phis2-ws/src/main/java/opensilex/service/dao/exception/PropertySemanticInconsistencyException.java
  phis2-ws/src/main/java/opensilex/service/dao/exception/SemanticInconsistencyException.java
  phis2-ws/src/main/java/opensilex/service/dao/exception/TypeNotInDomainException.java
  phis2-ws/src/main/java/opensilex/service/dao/exception/TypeNotInRangeException.java
  phis2-ws/src/main/java/opensilex/service/dao/exception/UnknownUriException.java
  phis2-ws/src/main/java/opensilex/service/dao/exception/UnknownUriOfTypeException.java
  phis2-ws/src/main/java/opensilex/service/dao/exception/WrongTypeException.java
  phis2-ws/src/main/java/opensilex/service/dao/manager/Rdf4jDAO.java
  phis2-ws/src/main/java/opensilex/service/documentation/StatusCodeMsg.java
  phis2-ws/src/main/java/opensilex/service/model/ConcernedItem.java
  phis2-ws/src/main/java/opensilex/service/resource/AnnotationResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/EventResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/InfrastructureResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/RadiometricTargetResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/ResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/SensorResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/VocabularyResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/brapi/StudiesResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/dto/ConcernedItemWithLabelsDTO.java
  phis2-ws/src/main/java/opensilex/service/resource/dto/event/EventDTO.java
  phis2-ws/src/main/java/opensilex/service/resource/dto/event/EventPostDTO.java
  phis2-ws/src/main/java/opensilex/service/utils/POSTResultsReturn.java
  phis2-ws/src/main/java/opensilex/service/utils/UriGenerator.java
Labels: refactoring

#271 Environmental data : accept data from any type of device
  phis2-ws/src/main/java/opensilex/service/dao/DeviceDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/EnvironmentMeasureDAO.java
  phis2-ws/src/main/java/opensilex/service/ontology/Oeso.java
  phis2-ws/src/main/java/opensilex/service/utils/UriGenerator.java
Labels: new feature
