Repository OpenSILEX/phis-ws, pull requests merged in 2019-05, with the labels that each got.

#273 Add sensors search like
  phis2-ws/src/main/java/opensilex/service/dao/SensorDAO.java
  phis2-ws/src/main/java/opensilex/service/resource/SensorResourceService.java
Labels: major bug

#274 Add actuators search like
  phis2-ws/src/main/java/opensilex/service/dao/ActuatorDAO.java
  phis2-ws/src/main/java/opensilex/service/resource/ActuatorResourceService.java
Labels: major bug

#275 Add vectors search like
  phis2-ws/src/main/java/opensilex/service/dao/VectorDAO.java
  phis2-ws/src/main/java/opensilex/service/resource/VectorResourceService.java
Labels: major bug

#277 Change Date and Decimal number management in POST Data service
  phis2-ws/src/main/java/opensilex/service/configuration/DateFormat.java
  phis2-ws/src/main/java/opensilex/service/resource/dto/data/DataDTO.java
  phis2-ws/src/main/java/opensilex/service/resource/dto/data/DataPostDTO.java
Labels: enhancement, minor bug

#281 Annotation/fix issue with commas in body values
  phis2-ws/src/main/java/opensilex/service/dao/AnnotationDAO.java
  phis2-ws/src/main/java/opensilex/service/model/Annotation.java
Labels: minor bug

#282 fix error when scientific object property value is not an uri
  phis2-ws/src/main/java/opensilex/service/dao/ScientificObjectRdf4jDAO.java
  phis2-ws/src/main/java/opensilex/service/resource/ScientificObjectResourceService.java
Labels: major bug

#283 add deprecated annotations to Image and Dataset services
  phis2-ws/src/main/java/opensilex/service/resource/DatasetResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/ImageResourceService.java
Labels: enhancement

#284 Add /data/search GET service
  phis2-ws/src/main/java/opensilex/service/dao/DataDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/ProvenanceDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/manager/Rdf4jDAO.java
  phis2-ws/src/main/java/opensilex/service/resource/DataResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/dto/data/DataSearchDTO.java
  phis2-ws/src/main/java/opensilex/service/resource/dto/data/ObjectResourceDTO.java
  phis2-ws/src/main/java/opensilex/service/resource/dto/rdfResourceDefinition/RdfResourceDTO.java
  phis2-ws/src/main/java/opensilex/service/resource/dto/rdfResourceDefinition/RdfResourceDefinitionDTO.java
Labels: new feature

#285 Scientific object - GET : add like search for uri and label
  phis2-ws/src/main/java/opensilex/service/dao/ScientificObjectRdf4jDAO.java
  phis2-ws/src/main/java/opensilex/service/resource/ScientificObjectResourceService.java
Labels: minor bug

#286 replace phenome to opensilex
  phis2-ws/src/main/java/opensilex/service/documentation/DocumentationAnnotation.java
Labels: refactoring

#287 add @Singleton (fix warning)
  phis2-ws/src/main/java/opensilex/service/resource/brapi/CallsResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/brapi/StudiesResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/brapi/TokenResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/brapi/TraitsResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/brapi/VariableResourceService.java
Labels: minor bug

#289 Variables fix put
  phis2-ws/src/main/java/opensilex/service/dao/MethodDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/TraitDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/UnitDAO.java
  phis2-ws/src/main/java/opensilex/service/dao/VariableDAO.java
  phis2-ws/src/main/java/opensilex/service/resource/MethodResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/TraitResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/UnitResourceService.java
  phis2-ws/src/main/java/opensilex/service/resource/VariableResourceService.java
Labels: major bug
