Repository OpenSILEX/phis-ws, pull requests merged in 2019-01, with the labels that each got.

#176 GET Species
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/SpeciesDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/documentation/DocumentationAnnotation.java
  phis2-ws/src/main/java/phis2ws/service/resources/InfrastructureResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/ResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/SpeciesResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/species/SpeciesDTO.java
  phis2-ws/src/main/java/phis2ws/service/view/brapi/form/ResponseFormSpecies.java
  phis2-ws/src/main/java/phis2ws/service/view/brapi/results/ResultSpecies.java
  phis2-ws/src/main/java/phis2ws/service/view/model/phis/Species.java
Labels: new feature, refactoring

#184 experiments - search : fix date format rule
  phis2-ws/src/main/java/phis2ws/service/resources/ExperimentResourceService.java
Labels: minor bug

#183 Code coverage plugin
  phis2-ws/pom.xml
Labels: enhancement

#181 links experiment-variable and experiment-sensors
  phis2-ws/src/main/java/phis2ws/service/dao/phis/ExperimentDao.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/ExperimentDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/SensorDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/documentation/DocumentationAnnotation.java
  phis2-ws/src/main/java/phis2ws/service/ontologies/Vocabulary.java
  phis2-ws/src/main/java/phis2ws/service/resources/ExperimentResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/SensorResourceService.java
  phis2-ws/src/main/java/phis2ws/service/view/model/phis/Experiment.java
Labels: new feature

#185 GET Events
  .gitignore
  phis2-ws/src/main/java/phis2ws/service/configuration/DateFormat.java
  phis2-ws/src/main/java/phis2ws/service/configuration/DateFormats.java
  phis2-ws/src/main/java/phis2ws/service/dao/manager/DAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/EventDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/PropertyDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/RadiometricTargetDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/documentation/DocumentationAnnotation.java
  phis2-ws/src/main/java/phis2ws/service/ontologies/Oeev.java
  phis2-ws/src/main/java/phis2ws/service/ontologies/Time.java
  phis2-ws/src/main/java/phis2ws/service/ontologies/Xsd.java
  phis2-ws/src/main/java/phis2ws/service/resources/EventResourceService.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/ConcernItemDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/ConcernsItemWithLabelsDTO.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/event/EventDTO.java
  phis2-ws/src/main/java/phis2ws/service/utils/dates/Dates.java
  phis2-ws/src/main/java/phis2ws/service/view/brapi/form/ResponseFormEvent.java
  phis2-ws/src/main/java/phis2ws/service/view/brapi/results/ResultEvent.java
  phis2-ws/src/main/java/phis2ws/service/view/model/phis/ConcernItem.java
  phis2-ws/src/main/java/phis2ws/service/view/model/phis/Event.java
  phis2-ws/src/main/java/phis2ws/service/view/model/phis/Property.java
Labels: new feature

#198 remove the already existing vocabulary
  phis2-ws/src/main/java/phis2ws/service/ontologies/Vocabulary.java
Labels: major bug

#170 Add mongo transaction for environment data insertion
  phis2-ws/pom.xml
  phis2-ws/src/main/java/phis2ws/service/dao/mongo/EnvironmentDAOMongo.java
Labels: enhancement, question

#199 Experiment links to variables and sensors - clean and refactor
  phis2-ws/src/main/java/phis2ws/service/dao/phis/ExperimentDao.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/ExperimentDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/resources/ExperimentResourceService.java
Labels: refactoring

#187 Jena #1 - Use Jena for Trait/method/Uri/Variables INSERT and DELETE
  phis2-ws/pom.xml
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/MethodDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/TraitDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/UnitDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/VariableDaoSesame.java
Labels: refactoring

#188 Jena #2 - Use Jena for Vector INSERT and DELETE
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/VectorDAOSesame.java
Labels: refactoring

#189 Jena #3 - Use Jena for Sensor INSERT and DELETE
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/SensorDAOSesame.java
Labels: refactoring

#191 Jena #5 - Use Jena for Radiometric targets INSERT and DELETE
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/PropertyDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/RadiometricTargetDAOSesame.java
Labels: refactoring

#192 Jena #6 - Use Jena for Annotations INSERT and DELETE
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/AnnotationDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/resources/brapi/TokenResourceService.java
Labels: refactoring

#193 Jena #7 - Use Jena for Agronomical objects INSERT and DELETE
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/ScientificObjectDAOSesame.java
Labels: refactoring

#194 Jena #8 - Use Jena for Generic DAO (link update) INSERT and DELETE
  phis2-ws/src/main/java/phis2ws/service/dao/manager/DAOSesame.java
Labels: refactoring

#202 Jena #11 ExperimentDAOSesame : remove SPARQLUpdateBuilder and use Jena instead
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/ExperimentDAOSesame.java
Labels: refactoring

#195 Jena #9 - Use Jena for Documents INSERT and DELETE
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/DocumentDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/resources/dto/DocumentMetadataDTO.java
Labels: refactoring

#196 Jena #10 - Use Jena for Triplets Service INSERT and DELETE
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/TripletDAOSesame.java
Labels: refactoring

#197 Jena FINAL - Remove old SPARQLUpdateBuilder class
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/DocumentDaoSesame.java
  phis2-ws/src/main/java/phis2ws/service/utils/sparql/SPARQLUpdateBuilder.java
Labels: refactoring

#206 fix scientific objects creation
  phis2-ws/src/main/java/phis2ws/service/dao/phis/ScientificObjectDAO.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/ScientificObjectDAOSesame.java
Labels: major bug

#207 Scientific objects POST : add participatesIn
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/ScientificObjectDAOSesame.java
Labels: major bug

#208 fix layer generation
  phis2-ws/src/main/java/phis2ws/service/dao/phis/LayerDao.java
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/ScientificObjectDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/ontologies/GeoSPARQL.java
Labels: minor bug

#212 @phis.fr to @opensilex.org
  phis2-ws/src/main/java/phis2ws/service/dao/sesame/RadiometricTargetDAOSesame.java
  phis2-ws/src/main/java/phis2ws/service/documentation/DocumentationAnnotation.java
Labels: refactoring
